version: '3.7'
services:

  nethound-ui:
    build:
      context: ui
      dockerfile: Dockerfile
    container_name: nethound-ui
    ports:
    - 8501:8501
    networks:
    - nethound
    environment:
      NETHOUND_API_URL: http://nethound-rest-server:10456

  nethound-rest-server:
    build:
      context: api
      dockerfile: Dockerfile.rest
    container_name: nethound-rest-server
    ports:
    - 10456:10456
    networks:
    - nethound
    - timescale
    environment:
      PG_HOST: timescale-server
      PG_USER: nethound_admin
      PG_PASSWORD: development

  nethound-grpc-server:
    build:
      context: api
      dockerfile: Dockerfile.grpc
    container_name: nethound-grpc-server
    ports:
    - 50051:50051
    networks:
    - nethound
    - timescale
    environment:
      PG_HOST: timescale-server
      PG_USER: nethound_admin
      PG_PASSWORD: development

  nethound-client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: nethound-client
    networks:
    - nethound
    environment:
      NETHOUND_GRPC_HOST: nethound-grpc-server
      NETHOUND_GRPC_PORT: 50051
      MAX_BUFFER_SIZE: 10
      MONITOR_UPLOAD_SPEED: 'false'
      NETWORK_ID: f6c9f40b-7102-4dc1-9d40-ac82fbf335d6
      GRPC_SSL_ENABLED: 'false'

networks:
  timescale:
    name: timescale
  nethound:
    name: nethound