# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nethound.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nethound.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0enethound.proto\"R\n\nTimeseries\x12\x12\n\nnetwork_id\x18\x01 \x01(\t\x12\x10\n\x08start_ts\x18\x02 \x01(\t\x12\x13\n\x06\x65nd_ts\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_end_ts\"\xa8\x01\n\x0bNetworkStat\x12\x12\n\nnetwork_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64ownload_speed\x18\x02 \x01(\x02\x12\x15\n\rupload_tested\x18\x03 \x01(\x08\x12\x19\n\x0cupload_speed\x18\x04 \x01(\x02H\x00\x88\x01\x01\x12\x11\n\texec_time\x18\x05 \x01(\x02\x12\x17\n\x0f\x65vent_timestamp\x18\x06 \x01(\tB\x0f\n\r_upload_speed\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2|\n\x0fNethoundService\x12/\n\x12StreamNetworkStats\x12\x0c.NetworkStat\x1a\x07.Status\"\x00(\x01\x12\x38\n\x17StreamNetworkTimeseries\x12\x0b.Timeseries\x1a\x0c.NetworkStat\"\x00\x30\x01\x62\x06proto3'
)




_TIMESERIES = _descriptor.Descriptor(
  name='Timeseries',
  full_name='Timeseries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_id', full_name='Timeseries.network_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_ts', full_name='Timeseries.start_ts', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_ts', full_name='Timeseries.end_ts', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_end_ts', full_name='Timeseries._end_ts',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=18,
  serialized_end=100,
)


_NETWORKSTAT = _descriptor.Descriptor(
  name='NetworkStat',
  full_name='NetworkStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_id', full_name='NetworkStat.network_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_speed', full_name='NetworkStat.download_speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_tested', full_name='NetworkStat.upload_tested', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_speed', full_name='NetworkStat.upload_speed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exec_time', full_name='NetworkStat.exec_time', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_timestamp', full_name='NetworkStat.event_timestamp', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_upload_speed', full_name='NetworkStat._upload_speed',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=103,
  serialized_end=271,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=312,
)

_TIMESERIES.oneofs_by_name['_end_ts'].fields.append(
  _TIMESERIES.fields_by_name['end_ts'])
_TIMESERIES.fields_by_name['end_ts'].containing_oneof = _TIMESERIES.oneofs_by_name['_end_ts']
_NETWORKSTAT.oneofs_by_name['_upload_speed'].fields.append(
  _NETWORKSTAT.fields_by_name['upload_speed'])
_NETWORKSTAT.fields_by_name['upload_speed'].containing_oneof = _NETWORKSTAT.oneofs_by_name['_upload_speed']
DESCRIPTOR.message_types_by_name['Timeseries'] = _TIMESERIES
DESCRIPTOR.message_types_by_name['NetworkStat'] = _NETWORKSTAT
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timeseries = _reflection.GeneratedProtocolMessageType('Timeseries', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIES,
  '__module__' : 'nethound_pb2'
  # @@protoc_insertion_point(class_scope:Timeseries)
  })
_sym_db.RegisterMessage(Timeseries)

NetworkStat = _reflection.GeneratedProtocolMessageType('NetworkStat', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKSTAT,
  '__module__' : 'nethound_pb2'
  # @@protoc_insertion_point(class_scope:NetworkStat)
  })
_sym_db.RegisterMessage(NetworkStat)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'nethound_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)



_NETHOUNDSERVICE = _descriptor.ServiceDescriptor(
  name='NethoundService',
  full_name='NethoundService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamNetworkStats',
    full_name='NethoundService.StreamNetworkStats',
    index=0,
    containing_service=None,
    input_type=_NETWORKSTAT,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamNetworkTimeseries',
    full_name='NethoundService.StreamNetworkTimeseries',
    index=1,
    containing_service=None,
    input_type=_TIMESERIES,
    output_type=_NETWORKSTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETHOUNDSERVICE)

DESCRIPTOR.services_by_name['NethoundService'] = _NETHOUNDSERVICE

# @@protoc_insertion_point(module_scope)
