# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.stubs.nethound_pb2 as nethound__pb2


class NethoundServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamNetworkStats = channel.stream_unary(
                '/NethoundService/StreamNetworkStats',
                request_serializer=nethound__pb2.NetworkStat.SerializeToString,
                response_deserializer=nethound__pb2.Status.FromString,
                )
        self.StreamNetworkTimeseries = channel.unary_stream(
                '/NethoundService/StreamNetworkTimeseries',
                request_serializer=nethound__pb2.Timeseries.SerializeToString,
                response_deserializer=nethound__pb2.NetworkStat.FromString,
                )


class NethoundServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamNetworkStats(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNetworkTimeseries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NethoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamNetworkStats': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamNetworkStats,
                    request_deserializer=nethound__pb2.NetworkStat.FromString,
                    response_serializer=nethound__pb2.Status.SerializeToString,
            ),
            'StreamNetworkTimeseries': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNetworkTimeseries,
                    request_deserializer=nethound__pb2.Timeseries.FromString,
                    response_serializer=nethound__pb2.NetworkStat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NethoundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NethoundService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamNetworkStats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/NethoundService/StreamNetworkStats',
            nethound__pb2.NetworkStat.SerializeToString,
            nethound__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamNetworkTimeseries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/NethoundService/StreamNetworkTimeseries',
            nethound__pb2.Timeseries.SerializeToString,
            nethound__pb2.NetworkStat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
