
name: CI

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to ASN registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login docker.alpinesoftware.net --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          
      - name: Build and push gRPC server
        run: |
          docker build -t docker.alpinesoftware.net/nethound/grpc-server:latest -f Dockerfile.grpc api
          docker push docker.alpinesoftware.net/nethound/grpc-server:latest
      
      - name: Build and push API
        run: |
          docker build -t docker.alpinesoftware.net/nethound/rest-server:latest -f Dockerfile.rest api
          docker push docker.alpinesoftware.net/nethound/rest-server:latest
          
      - name: Build and push client
        run: |
          docker build -t docker.alpinesoftware.net/nethound/client:latest -f Dockerfile client
          docker push docker.alpinesoftware.net/nethound/client:latest
          
          docker build -t docker.alpinesoftware.net/nethound/client:latest-arm -f Dockerfile.arm client
          docker push docker.alpinesoftware.net/nethound/client:latest-arm
        
